language: node_js
node_js:
  - node
install:
  - npm ci
  - npm run bootstrap -- --ci
script:
  - npm run lint
  - npm test
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
