language: node_js
node_js:
  - node
install:
  - npm ci
  - npm run bootstrap -- --ci
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
    - stage: build
      script: npm run build
    - stage: deploy
      if: branch = master
      script: npm run deploy:client
